// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bitmex/positions.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace CrossTrader.Models.Remoting.BitMex {
  internal static partial class PositionsService
  {
    static readonly string __ServiceName = "crosstrader.bitmex.PositionsService";

    static readonly grpc::Marshaller<global::CrossTrader.Models.Remoting.InstrumentIdRequest> __Marshaller_crosstrader_InstrumentIdRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CrossTrader.Models.Remoting.InstrumentIdRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::CrossTrader.Models.Remoting.BitMex.PositionsResponse> __Marshaller_crosstrader_bitmex_PositionsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CrossTrader.Models.Remoting.BitMex.PositionsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::CrossTrader.Models.Remoting.InstrumentIdRequest, global::CrossTrader.Models.Remoting.BitMex.PositionsResponse> __Method_SubscribePositions = new grpc::Method<global::CrossTrader.Models.Remoting.InstrumentIdRequest, global::CrossTrader.Models.Remoting.BitMex.PositionsResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribePositions",
        __Marshaller_crosstrader_InstrumentIdRequest,
        __Marshaller_crosstrader_bitmex_PositionsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::CrossTrader.Models.Remoting.BitMex.PositionsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for PositionsService</summary>
    public partial class PositionsServiceClient : grpc::ClientBase<PositionsServiceClient>
    {
      /// <summary>Creates a new client for PositionsService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PositionsServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PositionsService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PositionsServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PositionsServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PositionsServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::CrossTrader.Models.Remoting.BitMex.PositionsResponse> SubscribePositions(global::CrossTrader.Models.Remoting.InstrumentIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubscribePositions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::CrossTrader.Models.Remoting.BitMex.PositionsResponse> SubscribePositions(global::CrossTrader.Models.Remoting.InstrumentIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscribePositions, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PositionsServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PositionsServiceClient(configuration);
      }
    }

  }
}
#endregion
